baseURL: "https://kyleadler.com/"
languageCode: "en-us"
title: "Kyle’s Engineering Blog"
theme: ["PaperMod"]
publishDir: "public"
contentDir: "content"  # Obsidian folder

markup:
  goldmark:
    renderer:
      unsafe: true # Allow HTML in markdown
    extensions:
      passthrough:
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - \(
            - \)
          - - $
            - $
        enable: true

taxonomies:
  tag: "tags" # Allow tags like "Engineering", "Software", etc.
  # category: "categories" # Allow categories like "Engineering", "Software", etc.

params:
  math: true # Enable math rendering for latex
  ShowReadingTime: true # Show estimated reading time for posts
  ShowBreadCrumbs: true # Enable breadcrumbs for navigation
  ShowPostNavLinks: true # Enable next/previous post links
  ShowCodeCopyButtons: true # Enable copy buttons for code blocks
  profileMode:
    enabled: true
    title: "Kyle's Engineering Blog" # optional default will be site title
    subtitle: "Welcome to my blog!" # optional
    imageUrl: "images/profile.jpg" # optional
    imageTitle: "Me holding a liquid rocket engine" # optional
    imageWidth: 240 # custom size
    imageHeight: 240 # custom size
    buttons:
      - name: About
        url: "/posts/about/"
      - name: Archive
        url: "/archive/"

    # homeInfoParams:
    #   Title: Welcome to my blog
    #   Content: This blog contains various information about my engineering journey, projects, and insights.

  socialIcons: # optional
    - name: "GitHub"
      url: "https://github.com/engkad"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/kyledadler"
    - name: "Youtube"
      url: "https://www.youtube.com/@engkad880"


menu:
  main:
    - identifier: "posts"
      name: "Posts"
      url: "/posts/"
      weight: 1

    - identifier: "archive"
      name: "Archive"
      url: "/archive/"
      weight: 2

    - identifier: "tags"
      name: "Tags"
      url: "/tags/"
      weight: 3

    - identifier: "search"
      name: "Search"
      url: "/search/"
      weight: 4

# add search functionality
outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search